# See https://docs.travis-ci.com/user/languages/cpp for defaults
language: cpp

# Send builds to the container-based infrastructure
sudo: false

# Add Linux and OS X to build matrix
os:
  - linux
  - osx

# As using container-based infrastructure, unable to use
# sudo make installdeps
addons:
  apt:
    packages:
    - build-essential
    - libsdl1.2-dev
    - libsdl-mixer1.2-dev

# Use brew on OS X to install dependencies
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update               ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl sdl_mixer; fi

# Add clang and gcc compiler to build matrix
compiler:
  - clang
  - gcc

# Add Debug and Release to build matrix 
env:
  matrix:
    - DEBUG=1
    - DEBUG=0

#
# Build and run test suite
#
script: make && make test

# Exclude gcc on OS X, it maps to clang on that platform
matrix:
  exclude:
    - os: osx
      compiler: gcc
