# makefile for lua standard library

# modified by Thatcher Ulrich <tu@tulrich.com> 7/24/2000 to compile under Win32

LUA= ../..

include $(LUA)/config.linux

# actually only used in liolib.c
EXTRA_DEFS= $(POPEN)

OBJS= linit.o ldblib.o liolib.o lmathlib.o lstrlib.o
SRCS= linit.c ldblib.c liolib.c lmathlib.c lstrlib.c

T= $(LUALIB)/lualib.lib

all: $T

$T: $(OBJS)
	$(AR) $@ $(OBJS)
#	$(RANLIB) $@

clean:
	rm -f $(OBJS) $T

co:
	co -q -f -M $(SRCS)

klean:	clean
	rm -f $(SRCS)
