# makefile for lua distribution (includes)

# modified by Thatcher Ulrich <tu@tulrich.com> 1/26/2001 to compile under Linux

LUA= ..

include $(LUA)/config

SRCS= lua.h lualib.h luadebug.h lauxlib.h

all:

clean:

co:
	co -q -f -M $(SRCS)

klean:	clean
	rm -f $(SRCS)
